import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Add the weights you need
  variable: "--font-lato", // Optional: custom CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Belayet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} antialiased container px-5 mx-auto`}>
        <Navbar />
        <main className="mx-auto">{children}</main>
      </body>
    </html>
  );
}
